echo ">>> Making pgpool"

for VALS in "PGPOOL_VERSION=3.3 PGPOOL_PACKAGE_VERSION=3.3.4 PG_CLIENT_MAJOR_VERSION=9.6 PG_CLIENT_VERSION=9.6 PG_CLIENT_PACKAGE_VERSION=9.6" \
            "PGPOOL_VERSION=3.3 PGPOOL_PACKAGE_VERSION=3.3.4 PG_CLIENT_MAJOR_VERSION=10.2 PG_CLIENT_VERSION=10 PG_CLIENT_PACKAGE_VERSION=10.2" \
            "PGPOOL_VERSION=3.6 PGPOOL_PACKAGE_VERSION=3.6 PG_CLIENT_MAJOR_VERSION=9.6 PG_CLIENT_VERSION=9.6 PG_CLIENT_PACKAGE_VERSION=9.6" \
            "PGPOOL_VERSION=3.6 PGPOOL_PACKAGE_VERSION=3.6 PG_CLIENT_MAJOR_VERSION=10.2 PG_CLIENT_VERSION=10 PG_CLIENT_PACKAGE_VERSION=10.2";  do
    eval $VALS
    
    FILE_FROM="./src/includes/dockerfile/Pgpool-$PGPOOL_VERSION.part.Dockerfile"
    FILE_TO="./src/Pgpool-$PGPOOL_VERSION-Postgres-$PG_CLIENT_MAJOR_VERSION.Dockerfile"
    
    template $FILE_FROM $FILE_TO $VALS
done