{{ range $i, $e := .Values.postgres.nodes }}
  {{ if .volume.definition }}
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: db-data-{{ $.Values.postDock.name }}-db-node-{{ $i }}
  labels:
    system: {{ $.Values.postDock.name }}-db
    node: node-{{ $i }}
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: {{ $e.volume.size }}
  persistentVolumeReclaimPolicy: {{ $e.volume.reclaimPolicy }}
{{ toYaml .volume.definition | indent 2 }}
  {{ end }}
{{ end }}
