echo ">>> Making barman"

for VALS in "BARMAN_VERSION=2.3;BARMAN_PACKAGE_VERSION=2.3-2.pgdg80+1;PG_CLIENT_MAJOR_VERSION=9.6;PG_CLIENT_VERSION=9.6;PG_CLIENT_PACKAGE_VERSION=9.6" \
            "BARMAN_VERSION=2.3;BARMAN_PACKAGE_VERSION=2.3-2.pgdg80+1;PG_CLIENT_MAJOR_VERSION=10.2;PG_CLIENT_VERSION=10;PG_CLIENT_PACKAGE_VERSION=10.2"; do
    eval $VALS
    echo ">>>>>> Making $VALS"
    
    FILE_FROM="./src/includes/dockerfile/Barman-$BARMAN_VERSION.part.Dockerfile"
    FILE_TO="./src/Barman-$BARMAN_VERSION-Postgres-$PG_CLIENT_MAJOR_VERSION.Dockerfile"
    
    flush $FILE_TO
    template $FILE_FROM $FILE_TO $VALS
done
