kind: PersistentVolume
apiVersion: v1
metadata:
  name: data-volume-1
  labels:
    type: local
spec:
  capacity:
    storage: 3Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/tmp/data-volume-1"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: data-claim-1
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: Pod
metadata:
  name: database-node1
  labels:
    name: database
    node: node1
spec:
  restartPolicy: Never
  containers:
    -
      name: database-node1
      image: paunin/postgresql-cluster-pgsql
      env: # those variables are not secret as it's just initial state of DB
        -
          name: "NODE_ID"
          value: "1"
        -
          name: "NODE_NAME"
          value: "node1"
        -
          name: "CLUSTER_NODE_NETWORK_NAME"
          value: "database-node1-service"
        -
          name: "POSTGRES_PASSWORD"
          value: "monkey_pass"
        -
          name: "POSTGRES_USER"
          value: "monkey_user"
        -
          name: "POSTGRES_DB"
          value: "monkey_db"
        -
          name: "CLUSTER_NAME"
          value: "pg_cluster"
        -
          name: "REPLICATION_DB"
          value: "replication_db"
        -
          name: "REPLICATION_USER"
          value: "replication_user"
        -
          name: "REPLICATION_PASSWORD"
          value: "replication_pass"
        -
          name: "CONFIGS"
          value: "autovacuum:on"
      ports:
        -
          containerPort: 5432
      volumeMounts:
        - mountPath:  /var/lib/postgresql/data
          name: pg-data-volume
  volumes:
    - name: pg-data-volume
      persistentVolumeClaim:
        claimName: data-claim-1

---
apiVersion: v1
kind: Service
metadata:
  name: database-node1-service
  labels:
    name: database
    node: node1
spec:
  ports:
    - port: 5432
  selector:
    name: database
    node: node1